#!/usr/bin/env bash

# Script variables
script=$1

# Image variables
image=$2

# Print usage
function usage(){
    echo "usage: mkapp <script> <image>"
    echo
    echo "args:"
    echo "    app:   path to executable        ex: myapp.sh"
    echo "    image: path to png image         ex: icarus.png"
}

# Check script args
[[ ! -f $script ]] && echo "script not found" && usage && exit 1

# Check image args
[[ ! -f $image ]] && echo "image not found" && usage && exit 1

# Make icon
icon=$(src/mkicon $image)

# Make app
app=$(src/mkosx $script $icon)

# Print results
[[ $? -gt 0 ]] && echo "error creating app" && exit 1
echo $app
