#!/usr/bin/env bash

# Arguments
image=$1
base_name=$(basename -- "$image")
icon_name=${base_name%.*}

# Print usage
function usage(){
    echo "usage: mkicon <image>"
    echo
    echo "args:"
    echo "    image: 1024 x 1024 PNG image     ex: icarus.png"
}

# Check args
[[ ! -f $image || -z $icon_name ]] && usage && exit 1

# Make iconset directory
icns_dir=${icon_name}.iconset
mkdir ${icon_name}.iconset

# Create iconset images
dims=(16 32 64 128 256 512 1024)
for dim in ${dims[@]}
do
    i=$((i+1))
    sips -z $dim $dim $image --out ${icns_dir}/icon_${dim}x${dim}.png &> /dev/null
    [[ ! -z ${dims[$i]} ]] && sips -z ${dims[$i]} ${dims[$i]} $image \
        --out ${icns_dir}/icon_${dim}x${dim}@2x.png &> /dev/null
done

# Conver iconset to icon
iconutil -c icns ${icns_dir}

# Print results
[[ $? == 0 ]] && echo "${icon_name}.icns" || exit 1

# Cleanup
rm -R ${icon_name}.iconset